// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RatBot.Infrastructure.Data;

namespace RatBot.Infrastructure.Migrations;

[DbContext(typeof(BotDbContext))]
[Migration("20260717001600_ExpandMultiGuildOwnership")]
partial class ExpandMultiGuildOwnership
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.5");
#pragma warning restore 612, 618
    }
}
