// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260411180833_UpdateQuorumConfigTables")]
    partial class UpdateQuorumConfigTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Domain.Entities.EmojiUsageCount", b =>
                {
                    b.Property<string>("EmojiId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts");
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumConfigEntity", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double>("QuorumProportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double precision");

                    b.HasKey("GuildId", "TargetType", "TargetId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "TargetType");

                    b.ToTable("QuorumConfigs", (string)null);
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumConfigRoleEntity", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId", "TargetType", "TargetId", "RoleId");

                    b.ToTable("QuorumConfigRoles", (string)null);
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumConfigRoleEntity", b =>
                {
                    b.HasOne("RatBot.Infrastructure.Configuration.Quorum.QuorumConfigEntity", null)
                        .WithMany("Roles")
                        .HasForeignKey("GuildId", "TargetType", "TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatBot.Infrastructure.Configuration.Quorum.QuorumConfigEntity", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
