// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RatBot.Infrastructure.Data;

#nullable disable

namespace RatBot.Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260624195549_AddTemporaryPingRole")]
    partial class AddTemporaryPingRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RatBot.Domain.Adventure.AdventureForumThreadLink", b =>
                {
                    b.Property<int>("ScorePartIndex")
                        .HasColumnType("integer");

                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint");

                    b.HasKey("ScorePartIndex");

                    b.HasIndex("ScorePartIndex")
                        .IsUnique();

                    b.HasIndex("ThreadId")
                        .IsUnique();

                    b.ToTable("AdventureForumThreadLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdventureForumThreadLinks_ScorePartIndex", "\"ScorePartIndex\" >= 1 AND \"ScorePartIndex\" <= 20");
                        });
                });

            modelBuilder.Entity("RatBot.Domain.Adventure.AdventureLeaderboardMessageState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastRenderHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AdventureLeaderboardMessageState", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Emoji.EmojiUsageCount", b =>
                {
                    b.Property<long>("EmojiId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageUsageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionUsageCount")
                        .HasColumnType("int");

                    b.HasKey("EmojiId");

                    b.ToTable("EmojiUsageCounts", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Meta.MetaProposalState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedPollAttempts")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastPublicationRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivation")
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<long>("OriginalThreadAuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("PollExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PollFinalizationRetries")
                        .HasColumnType("integer");

                    b.Property<long?>("PollMessageId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalAuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProposalThreadChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProposalTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ProposedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("PublicationErrorMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("PublicationRetryFailures")
                        .HasColumnType("integer");

                    b.Property<string>("Specification")
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("SuggestionThreadChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuggestionsForumChannelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<DateTimeOffset>("TrackedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VetoReason")
                        .HasMaxLength(1950)
                        .HasColumnType("character varying(1950)");

                    b.Property<DateTimeOffset?>("VetoedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("VetoedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("PollMessageId");

                    b.HasIndex("ProposalThreadChannelId");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestionThreadChannelId")
                        .IsUnique();

                    b.HasIndex("Status", "PollExpiresAtUtc");

                    b.ToTable("MetaProposalStates", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Meta.MetaSuggestionSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("CabinetChairRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("CabinetRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommitteeRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProposalsForumChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuggestionsForumChannelId")
                        .HasColumnType("bigint");

                    b.HasKey("GuildId");

                    b.ToTable("MetaSuggestionSettings", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Moderation.AutobannedUser", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("BannedUser")
                        .HasColumnType("bigint");

                    b.Property<long>("Moderator")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "BannedUser");

                    b.HasIndex("BannedUser");

                    b.HasIndex("GuildId");

                    b.HasIndex("Moderator");

                    b.ToTable("AutobannedUsers", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Moderation.ImageSpamSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("BurstDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredAttachmentCount")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredChannelCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ImageSpamSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImageSpamSettings_BurstDurationSeconds_Positive", "\"BurstDurationSeconds\" > 0");

                            t.HasCheckConstraint("CK_ImageSpamSettings_RequiredAttachmentCount_Positive", "\"RequiredAttachmentCount\" > 0");

                            t.HasCheckConstraint("CK_ImageSpamSettings_RequiredChannelCount_Positive", "\"RequiredChannelCount\" > 0");
                        });
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<double>("Proportion")
                        .HasPrecision(6, 4)
                        .HasColumnType("double precision");

                    b.HasKey("GuildId", "TargetType", "TargetId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "TargetType");

                    b.ToTable("QuorumConfigs", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettingsRole", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("TargetType")
                        .HasColumnType("integer");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    b.HasKey("GuildId", "TargetType", "TargetId", "Id");

                    b.ToTable("QuorumConfigRoles", (string)null);
                });

            modelBuilder.Entity("RatBot.Domain.RoleColours.MemberColourPreference", b =>
                {
                    b.Property<Guid>("PreferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PreferenceId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MemberColourPreferences", null, t =>
                        {
                            t.HasCheckConstraint("CK_MemberColourPreferences_ConfiguredOption_SelectedOption_NotNull", "(\"Kind\" <> 1) OR (\"SelectedOptionId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MemberColourPreferences_NoColour_SelectedOption_Null", "(\"Kind\" <> 2) OR (\"SelectedOptionId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("RatBot.Domain.RoleColours.RoleColourOption", b =>
                {
                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DisplayRoleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NormalisedKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SourceRoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OptionId");

                    b.HasIndex("DisplayRoleId")
                        .IsUnique();

                    b.HasIndex("NormalisedKey")
                        .IsUnique();

                    b.HasIndex("SourceRoleId", "DisplayRoleId")
                        .IsUnique();

                    b.ToTable("RoleColourOptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_RoleColourOptions_DifferentRoles", "\"SourceRoleId\" <> \"DisplayRoleId\"");

                            t.HasCheckConstraint("CK_RoleColourOptions_Key_NotBlank", "length(btrim(\"Key\")) > 0");

                            t.HasCheckConstraint("CK_RoleColourOptions_Label_NotBlank", "length(btrim(\"Label\")) > 0");
                        });
                });

            modelBuilder.Entity("RatBot.Domain.TemporaryPingRole.TemporaryPingRoleSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TemporaryPingRoleSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemporaryPingRoleSettings_SingletonId", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettingsRole", b =>
                {
                    b.HasOne("RatBot.Domain.Quorum.QuorumSettings", null)
                        .WithMany("Roles")
                        .HasForeignKey("GuildId", "TargetType", "TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatBot.Domain.RoleColours.MemberColourPreference", b =>
                {
                    b.HasOne("RatBot.Domain.RoleColours.RoleColourOption", null)
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RatBot.Domain.Quorum.QuorumSettings", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
